# Generated by Django 4.2 on 2025-10-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for this service', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for this service', max_digits=10, null=True),
        ),
    ]
