# Generated by Django 4.2 on 2025-10-31 07:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_productcategory_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Preset name (e.g., 'Simple Extraction', 'Surgical Extraction')", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Optional description (e.g., 'For complicated cases requiring sutures')")),
                ('is_default', models.BooleanField(default=False, help_text='Auto-apply this preset when service is selected in treatment record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Dentist who owns this preset (private)', on_delete=django.db.models.deletion.CASCADE, related_name='service_presets', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service this preset applies to', on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='services.service')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePresetProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Default quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, help_text='Optional notes about this product in this preset', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('preset', models.ForeignKey(help_text='Parent preset', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.servicepreset')),
                ('product', models.ForeignKey(help_text='Product to include in preset', on_delete=django.db.models.deletion.PROTECT, to='services.product')),
            ],
            options={
                'ordering': ['order', 'product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='servicepresetproduct',
            index=models.Index(fields=['preset'], name='preset_prod_preset_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepresetproduct',
            unique_together={('preset', 'product')},
        ),
        migrations.AddIndex(
            model_name='servicepreset',
            index=models.Index(fields=['service', 'created_by'], name='preset_svc_user_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepreset',
            index=models.Index(fields=['created_by'], name='preset_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicepreset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('service', 'created_by'), name='unique_default_preset_per_service_per_user'),
        ),
    ]
