# Generated by Django 4.2 on 2025-10-05 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient Portal Access',
                'verbose_name_plural': 'Patient Portal Access Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Portal Session',
                'verbose_name_plural': 'Patient Portal Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['email', 'code'], name='portal_email_code_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['expires_at'], name='portal_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['created_at'], name='portal_created_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalsession',
            index=models.Index(fields=['session_key'], name='portal_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalsession',
            index=models.Index(fields=['email'], name='portal_session_email_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalsession',
            index=models.Index(fields=['expires_at'], name='portal_session_expires_idx'),
        ),
    ]
