# Generated by Django 4.2 on 2025-10-21 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_portal', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientportalsession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientportalaccess',
            name='verified_patient',
            field=models.ForeignKey(blank=True, help_text='Selected patient after OTP verification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_verifications', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patientportalsession',
            index=models.Index(fields=['session_key'], name='portal_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalsession',
            index=models.Index(fields=['email'], name='portal_session_email_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalsession',
            index=models.Index(fields=['expires_at'], name='portal_session_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['email', 'code'], name='portal_email_code_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['expires_at'], name='portal_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['created_at'], name='portal_created_idx'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['purpose'], name='portal_purpose_idx'),
        ),
    ]
