# Generated by Django 4.2 on 2025-10-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientportalaccess',
            name='purpose',
            field=models.CharField(choices=[('portal', 'Patient Portal Login'), ('booking', 'Appointment Booking Verification')], default='portal', help_text='What this code is being used for', max_length=10),
        ),
        migrations.AddField(
            model_name='patientportalaccess',
            name='verified_patient',
            field=models.ForeignKey(blank=True, help_text='Selected patient after OTP verification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_verifications', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patientportalaccess',
            index=models.Index(fields=['purpose'], name='portal_purpose_idx'),
        ),
    ]
