# Generated by Django 4.2 on 2025-10-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_patientportalaccess_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientportalsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
