# Generated by Django 4.2 on 2025-10-28 02:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_productcategory_product_and_more'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Service base fee (must be within service price range)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity used', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of use (snapshot for historical accuracy)', max_digits=10)),
                ('notes', models.CharField(blank=True, help_text="Optional notes (e.g., 'Extra anesthesia - patient anxiety')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='appointments.paymentitem')),
                ('product', models.ForeignKey(help_text='Product/supply used', on_delete=django.db.models.deletion.PROTECT, to='services.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentitemproduct',
            index=models.Index(fields=['payment_item'], name='pmt_item_prod_pmt_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentitemproduct',
            index=models.Index(fields=['product'], name='pmt_item_prod_prod_idx'),
        ),
    ]
