# Generated by Django 4.2 on 2025-10-29 02:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_productcategory_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_alter_paymentitem_price_paymentitemproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical observations, diagnosis, procedures performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(help_text='Related appointment', on_delete=django.db.models.deletion.CASCADE, related_name='treatment_record', to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treatment_records', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_treatment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecordService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes specific to this service')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('treatment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='appointments.treatmentrecord')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('treatment_record', 'service')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecordProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, help_text='Notes about product usage', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.product')),
                ('treatment_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='appointments.treatmentrecordservice')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecordAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(help_text='JSON object describing what changed')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=50)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('treatment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='appointments.treatmentrecord')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='services_performed',
            field=models.ManyToManyField(help_text='Services actually performed during appointment', related_name='treatment_records', through='appointments.TreatmentRecordService', to='services.service'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecordauditlog',
            index=models.Index(fields=['treatment_record'], name='treat_audit_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['appointment'], name='treatment_rec_appt_idx'),
        ),
    ]
