# Generated by Django 4.2 on 2025-10-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_treatmentrecord_treatmentrecordservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='procedures',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
    ]
