# Generated by Django 4.2 on 2025-10-11 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_appointment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
