# Generated by Django - manual migration
from django.db import migrations, models
import secrets


def generate_unique_tokens(apps, schema_editor):
    """Generate unique tokens for all existing appointments"""
    Appointment = apps.get_model('appointments', 'Appointment')
    
    for appointment in Appointment.objects.all():
        # Generate unique token
        while True:
            token = secrets.token_urlsafe(16)
            # Check if token already exists
            if not Appointment.objects.filter(reschedule_token=token).exists():
                appointment.reschedule_token = token
                appointment.save(update_fields=['reschedule_token'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_diagnosis_and_more'),
    ]

    operations = [
        # Step 1: Add field as nullable with no constraints
        migrations.AddField(
            model_name='appointment',
            name='reschedule_token',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Unique token for patient self-service actions',
                max_length=32,
                null=True  # Allow null initially
            ),
        ),
        # Step 2: Generate tokens for existing records
        migrations.RunPython(
            generate_unique_tokens,
            reverse_code=migrations.RunPython.noop
        ),
        # Step 3: Make field non-nullable
        migrations.AlterField(
            model_name='appointment',
            name='reschedule_token',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Unique token for patient self-service actions',
                max_length=32,
            ),
        ),
        # Step 4: Add index separately (without unique constraint first)
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['reschedule_token'], name='appt_reschedule_token_idx'),
        ),
        # Step 5: Add unique constraint separately
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(
                fields=['reschedule_token'],
                name='unique_reschedule_token'
            ),
        ),
    ]