# Generated by Django 4.2 on 2025-11-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_remove_appointment_unique_reschedule_token_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_reschedule_token',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_reschedule_token_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reschedule_token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for patient self-service actions', max_length=32, unique=True),
        ),
    ]
